/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package unilak;

import java.util.*;

/**
 *
 * @author ARMAND
 */
public class SellingForm extends javax.swing.JFrame {

    /**
     * Creates new form SellingForm
     */
    public SellingForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        price_shoes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        price_watches = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price_hand = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        price_phone = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        price_tablets = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        shoesBox = new javax.swing.JCheckBox();
        watche_Box = new javax.swing.JCheckBox();
        hand_Box = new javax.swing.JCheckBox();
        mobile_Box = new javax.swing.JCheckBox();
        smart_Box = new javax.swing.JCheckBox();
        qty_shoes = new javax.swing.JTextField();
        qty_watches = new javax.swing.JTextField();
        qty_handBags = new javax.swing.JTextField();
        qty_mobile_phones = new javax.swing.JTextField();
        qty_smart = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        delivery_loc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        price_shoes.setText("20000");

        jLabel3.setText("Rwf");

        price_watches.setText("30000");

        jLabel6.setText("Rwf");

        price_hand.setText("40000");

        jLabel9.setText("Rwf");

        price_phone.setText("70000");

        jLabel12.setText("Rwf");

        price_tablets.setText("65000");

        jLabel15.setText("Rwf");

        shoesBox.setText("SHOES");

        watche_Box.setText("WATCHES");

        hand_Box.setText("HAND BAGS");

        mobile_Box.setText("MOBILE  PHONES");

        smart_Box.setText("SMART TABLETS");

        qty_handBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_handBagsActionPerformed(evt);
            }
        });

        jLabel1.setText("Qty in Number");

        jLabel5.setText("Delivery Location");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delivery_loc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---SELECT---", "KIGALI", "HUYE", "NYAGATARE", "OTHER" }));

        jLabel2.setText("Price per item");

        jLabel4.setText("Items");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoesBox)
                    .addComponent(watche_Box)
                    .addComponent(smart_Box)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mobile_Box, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(hand_Box)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(price_shoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(qty_shoes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(price_watches, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(qty_smart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(qty_mobile_phones, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(qty_handBags, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(qty_watches, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(price_hand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(price_phone)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(95, 95, 95))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(price_tablets, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delivery_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoesBox)
                            .addComponent(price_shoes)
                            .addComponent(jLabel3)
                            .addComponent(qty_shoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(watche_Box)
                            .addComponent(price_watches)
                            .addComponent(jLabel6)
                            .addComponent(qty_watches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hand_Box)
                            .addComponent(price_hand)
                            .addComponent(jLabel9)
                            .addComponent(qty_handBags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile_Box)
                            .addComponent(price_phone)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty_mobile_phones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smart_Box)
                            .addComponent(price_tablets)
                            .addComponent(jLabel15)
                            .addComponent(qty_smart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(delivery_loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qty_handBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_handBagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_handBagsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        List<String> list = new ArrayList<String>();
        double totalAmount = 0;
        double freight=0;

        if (shoesBox.isSelected()) {
            double tot = Double.parseDouble(qty_shoes.getText()) * Double.parseDouble(price_shoes.getText());
            double discount = 0;
            double bulk = 0;
            double totalAfterTax = 0;

            list.add("------------ITEMS ORDERED---------------\n\n");

            if (Double.parseDouble(qty_shoes.getText()) > 50) {
                discount = tot - (tot * 10) / 100;
                totalAfterTax = discount - (discount * 9) / 100;

            } else if (Double.parseDouble(qty_shoes.getText()) > 20 && Double.parseDouble(qty_shoes.getText()) <= 50) {
                discount = tot - (tot * 5) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else {
                totalAfterTax = tot - (tot * 9) / 100;
            }

            if (tot > 2000000) {
                bulk = tot - (tot * 8) / 100;
                totalAfterTax = totalAfterTax - (bulk - (bulk * 9) / 100);
            }
            totalAmount = totalAmount + totalAfterTax;
            list.add("SHOES    " + qty_shoes.getText() + " Qty" + "=====Rwf " + tot + "     Discount= " + discount + " Bulk= " + bulk + " Total after tax= " + totalAfterTax);
        }
        if (watche_Box.isSelected()) {
            double tot = Double.parseDouble(qty_watches.getText()) * Double.parseDouble(price_watches.getText());
            double discount = 0;
            double bulk = 0;
            double totalAfterTax = 0;

            if ((Double.parseDouble(qty_watches.getText())) > 50&& (tot>2000000)) {
                discount = tot - (tot * 10) / 100;
                bulk=discount-(discount*8)/100;
                totalAfterTax = bulk - (bulk * 9) / 100;
            } else if (Double.parseDouble(qty_watches.getText()) > 20 && Double.parseDouble(qty_watches.getText()) <= 50&&tot>2000000) {
                discount = tot - (tot * 5) / 100;
                bulk=discount-(discount*8)/100;
                totalAfterTax = bulk - (bulk * 9) / 100;
                //totalAfterTax = discount - (discount * 9) / 100;
            } else {
                totalAfterTax = tot - (tot * 9) / 100;
            }
//            if (tot > 2000000) {
//                bulk = tot - (tot * 8) / 100;
//                totalAfterTax = totalAfterTax - (bulk - (bulk * 9) / 100);
//            }
            totalAmount = totalAmount + totalAfterTax;
            list.add("\nWATCHES     " + qty_watches.getText() + " Qty" + "=====Rwf " + tot + "     Discount= " + discount + " Bulk= " + bulk + " Total after tax= " + totalAfterTax);
        }
        if (hand_Box.isSelected()) {
            double tot = Double.parseDouble(qty_handBags.getText()) * Double.parseDouble(price_hand.getText());
            double discount = 0;
            double bulk = 0;
            double totalAfterTax = 0;
            if (Double.parseDouble(qty_handBags.getText()) > 50) {
                discount = tot - (tot * 10) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else if (Double.parseDouble(qty_handBags.getText()) > 20 && Double.parseDouble(qty_handBags.getText()) <= 50) {
                discount = tot - (tot * 5) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else {
                totalAfterTax = tot - (tot * 9) / 100;
            }
            if (tot > 2000000) {
                bulk = tot - (tot * 8) / 100;
                totalAfterTax = totalAfterTax - (bulk - (bulk * 9) / 100);
            }
            totalAmount = totalAmount + totalAfterTax;
            list.add("\nHAND BAGS    " + qty_handBags.getText() + " Qty" + "=====Rwf " + tot + "     Discount= " + discount + " Bulk= " + bulk + " Total after tax= " + totalAfterTax);
        }

        if (mobile_Box.isSelected()) {
            double tot = Double.parseDouble(qty_mobile_phones.getText()) * Double.parseDouble(price_phone.getText());
            double discount = 0;
            double bulk = 0;
            double totalAfterTax = 0;
            if (Double.parseDouble(qty_mobile_phones.getText()) > 50) {
                discount = tot - (tot * 10) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else if (Double.parseDouble(qty_mobile_phones.getText()) > 20 && Double.parseDouble(qty_mobile_phones.getText()) <= 50) {
                discount = tot - (tot * 5) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else {
                totalAfterTax = tot - (tot * 9) / 100;
            }
            if (tot > 2000000) {
                bulk = tot - (tot * 8) / 100;
                totalAfterTax = totalAfterTax - (bulk - (bulk * 9) / 100);
            }
            totalAmount = totalAmount + totalAfterTax;
            list.add("\nMOBILE PHONES    " + qty_mobile_phones.getText() + " Qty" + "=====Rwf " + tot + "     Discount= " + discount + " Bulk= " + bulk + " Total after tax= " + totalAfterTax);
        }
        if (smart_Box.isSelected()) {
            double tot = Double.parseDouble(qty_smart.getText()) * Double.parseDouble(price_tablets.getText());
            double discount = 0;
            double bulk = 0;
            double totalAfterTax = 0;
            if (Double.parseDouble(qty_smart.getText()) > 50) {
                discount = tot - (tot * 10) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else if (Double.parseDouble(qty_smart.getText()) > 20 && Double.parseDouble(qty_smart.getText()) <= 50) {
                discount = tot - (tot * 5) / 100;
                totalAfterTax = discount - (discount * 9) / 100;
            } else {
                totalAfterTax = tot - (tot * 9) / 100;
            }
            if (tot > 2000000) {
                bulk = tot - (tot * 8) / 100;
                totalAfterTax = totalAfterTax - (bulk - (bulk * 9) / 100);
            }
            totalAmount = totalAmount + totalAfterTax;
            list.add("\nSMART TABLETS    " + qty_smart.getText() + " Qty" + "=====Rwf " + tot + "     Discount= " + discount + " Bulk= " + bulk + " Total after tax= " + totalAfterTax);
        }
        String loc=delivery_loc.getSelectedItem().toString();
        if(loc.equalsIgnoreCase("KIGALI")){
            freight=2000;            
        }if(loc.equalsIgnoreCase("HUYE")){
            freight=4000;
        }if(loc.equalsIgnoreCase("NYAGATARE")){
            freight=3000;
        }if(loc.equalsIgnoreCase("OTHER")){
            freight=12000;
        }
        totalAmount=totalAmount+freight;
        
        list.add("\n\n\nFREIGHT                 "+freight);
        list.add("\nTOTAL AMOUNT            "+totalAmount);
        area.setText(list.toString());
      


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellingForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox delivery_loc;
    private javax.swing.JCheckBox hand_Box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox mobile_Box;
    private javax.swing.JLabel price_hand;
    private javax.swing.JLabel price_phone;
    private javax.swing.JLabel price_shoes;
    private javax.swing.JLabel price_tablets;
    private javax.swing.JLabel price_watches;
    private javax.swing.JTextField qty_handBags;
    private javax.swing.JTextField qty_mobile_phones;
    private javax.swing.JTextField qty_shoes;
    private javax.swing.JTextField qty_smart;
    private javax.swing.JTextField qty_watches;
    private javax.swing.JCheckBox shoesBox;
    private javax.swing.JCheckBox smart_Box;
    private javax.swing.JCheckBox watche_Box;
    // End of variables declaration//GEN-END:variables
}
